application: romanandreg
version: 1
api_version: 1
runtime: python

handlers:
- url: /stylesheets
  static_dir: stylesheets
- url: /javascripts
  static_dir: javascripts
- url: /images
  static_dir: images
- url: /.*
  script: controller.py